version: "3.9"
services:
  nginx:
    image: peerapach/distroless/nginx:${NGINX_VERSION}
    build:
      context: .
      dockerfile: ${PWD}/Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}      